var classes = [
    {
        "name": "Lib\\Controller",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "redirect",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Lib\\Http\\Request",
            "Twig\\Loader\\FilesystemLoader",
            "Twig\\Environment",
            "Cocur\\Slugify\\Slugify",
            "Twig\\TwigFilter",
            "Lib\\Http\\HtmlResponse",
            "Lib\\Http\\RedirectResponse"
        ],
        "parents": [],
        "lcom": 3,
        "length": 32,
        "vocabulary": 16,
        "volume": 128,
        "difficulty": 2.65,
        "effort": 339.69,
        "level": 0.38,
        "bugs": 0.04,
        "time": 19,
        "intelligentContent": 48.23,
        "number_operators": 9,
        "number_operands": 23,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 4,
        "loc": 28,
        "lloc": 24,
        "mi": 82.64,
        "mIwoC": 55,
        "commentWeight": 27.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.08,
        "relativeSystemComplexity": 10.08,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3.25,
        "totalSystemComplexity": 30.25,
        "package": "Lib\\",
        "pageRank": 0.1,
        "afferentCoupling": 4,
        "efferentCoupling": 7,
        "instability": 0.64,
        "violations": {}
    },
    {
        "name": "Lib\\Model",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "dbConnect",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "PDO"
        ],
        "parents": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 11,
        "volume": 51.89,
        "difficulty": 4.8,
        "effort": 249.08,
        "level": 0.21,
        "bugs": 0.02,
        "time": 14,
        "intelligentContent": 10.81,
        "number_operators": 7,
        "number_operands": 8,
        "number_operators_unique": 6,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 60.2,
        "mIwoC": 60.2,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 4.33,
        "package": "Lib\\",
        "pageRank": 0.06,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Lib\\Http\\HtmlResponse",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Lib\\Http\\Response"
        ],
        "parents": [
            "Lib\\Http\\Response"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 1,
        "effort": 7.92,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 7.92,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 1,
        "loc": 14,
        "lloc": 13,
        "mi": 89.39,
        "mIwoC": 69.27,
        "commentWeight": 20.12,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 0.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Lib\\Http\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Lib\\Http\\Response",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 6,
        "lloc": 5,
        "mi": 200.56,
        "mIwoC": 171,
        "commentWeight": 29.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Lib\\Http\\",
        "pageRank": 0.29,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Lib\\Http\\RedirectResponse",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Lib\\Http\\Response"
        ],
        "parents": [
            "Lib\\Http\\Response"
        ],
        "lcom": 1,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 1.67,
        "effort": 27.09,
        "level": 0.6,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 9.75,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 1,
        "loc": 14,
        "lloc": 13,
        "mi": 87.2,
        "mIwoC": 67.09,
        "commentWeight": 20.12,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 0.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Lib\\Http\\",
        "pageRank": 0.07,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Lib\\Http\\JsonRespnse",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "send",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Lib\\Http\\Response"
        ],
        "parents": [
            "Lib\\Http\\Response"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 1,
        "effort": 7.92,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 7.92,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 1,
        "loc": 14,
        "lloc": 13,
        "mi": 89.39,
        "mIwoC": 69.27,
        "commentWeight": 20.12,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 0.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Lib\\Http\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Lib\\Http\\Request",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getQuery",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPost",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getServer",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMethod",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUri",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 26,
        "vocabulary": 10,
        "volume": 86.37,
        "difficulty": 3.64,
        "effort": 314.63,
        "level": 0.27,
        "bugs": 0.03,
        "time": 17,
        "intelligentContent": 23.71,
        "number_operators": 9,
        "number_operands": 17,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 6,
        "loc": 39,
        "lloc": 33,
        "mi": 81.59,
        "mIwoC": 53.05,
        "commentWeight": 28.55,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5.5,
        "relativeSystemComplexity": 5.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 33,
        "totalSystemComplexity": 33,
        "package": "Lib\\Http\\",
        "pageRank": 0.11,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Lib\\Router\\RouterException",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 202.94,
        "mIwoC": 171,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Lib\\Router\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Lib\\Router\\Route",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "match",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "paramMatch",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "call",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Lib\\Http\\Request",
            "this"
        ],
        "parents": [],
        "lcom": 1,
        "length": 67,
        "vocabulary": 22,
        "volume": 298.78,
        "difficulty": 5.44,
        "effort": 1626.7,
        "level": 0.18,
        "bugs": 0.1,
        "time": 90,
        "intelligentContent": 54.88,
        "number_operators": 18,
        "number_operands": 49,
        "number_operators_unique": 4,
        "number_operands_unique": 18,
        "cloc": 7,
        "loc": 48,
        "lloc": 41,
        "mi": 74.97,
        "mIwoC": 47.08,
        "commentWeight": 27.88,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 7,
        "relativeSystemComplexity": 7,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 28,
        "totalSystemComplexity": 28,
        "package": "Lib\\Router\\",
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Lib\\Router\\Router",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Lib\\Router\\Route"
        ],
        "parents": [],
        "lcom": 1,
        "length": 27,
        "vocabulary": 11,
        "volume": 93.4,
        "difficulty": 4.13,
        "effort": 385.29,
        "level": 0.24,
        "bugs": 0.03,
        "time": 21,
        "intelligentContent": 22.64,
        "number_operators": 5,
        "number_operands": 22,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 6,
        "loc": 30,
        "lloc": 24,
        "mi": 87.63,
        "mIwoC": 55.69,
        "commentWeight": 31.94,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 10,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 30,
        "package": "Lib\\Router\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Src\\Controller\\HomeController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "admin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "about",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Lib\\Controller"
        ],
        "parents": [
            "Lib\\Controller"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 0.75,
        "effort": 15.67,
        "level": 1.33,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 27.86,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 2,
        "loc": 18,
        "lloc": 16,
        "mi": 89.04,
        "mIwoC": 64.36,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 7.5,
        "package": "Src\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Src\\Controller\\SecurityController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Lib\\Controller",
            "Lib\\Http\\RedirectResponse"
        ],
        "parents": [
            "Lib\\Controller"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 9,
        "volume": 41.21,
        "difficulty": 3.2,
        "effort": 131.87,
        "level": 0.31,
        "bugs": 0.01,
        "time": 7,
        "intelligentContent": 12.88,
        "number_operators": 5,
        "number_operands": 8,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 4,
        "loc": 18,
        "lloc": 14,
        "mi": 96.78,
        "mIwoC": 63.42,
        "commentWeight": 33.35,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 9.5,
        "package": "Src\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Src\\Controller\\CommentController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "commentAdmin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Lib\\Controller",
            "Src\\Model\\Comment",
            "Src\\Model\\Comment",
            "Src\\Model\\Comment"
        ],
        "parents": [
            "Lib\\Controller"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 11,
        "volume": 103.78,
        "difficulty": 4.31,
        "effort": 447.56,
        "level": 0.23,
        "bugs": 0.03,
        "time": 25,
        "intelligentContent": 24.07,
        "number_operators": 7,
        "number_operands": 23,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 8,
        "loc": 31,
        "lloc": 23,
        "mi": 91.46,
        "mIwoC": 56.04,
        "commentWeight": 35.41,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 25.44,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 76.33,
        "package": "Src\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Src\\Controller\\ChapterController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "chapters",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "chapter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lastChapter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "list",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Lib\\Controller",
            "Src\\Model\\Chapter",
            "Src\\Model\\Chapter",
            "Src\\Model\\Comment",
            "Src\\Model\\Chapter",
            "Src\\Model\\Chapter"
        ],
        "parents": [
            "Lib\\Controller"
        ],
        "lcom": 3,
        "length": 100,
        "vocabulary": 30,
        "volume": 490.69,
        "difficulty": 8.75,
        "effort": 4293.53,
        "level": 0.11,
        "bugs": 0.16,
        "time": 239,
        "intelligentContent": 56.08,
        "number_operators": 30,
        "number_operands": 70,
        "number_operators_unique": 6,
        "number_operands_unique": 24,
        "cloc": 9,
        "loc": 51,
        "lloc": 42,
        "mi": 75.23,
        "mIwoC": 44.94,
        "commentWeight": 30.29,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 100.53,
        "totalStructuralComplexity": 600,
        "totalDataComplexity": 3.18,
        "totalSystemComplexity": 603.18,
        "package": "Src\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Src\\Model\\Chapter",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getChapters",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getChapter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLastChapter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getChaptersAdmin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Lib\\Model",
            "static",
            "static",
            "static",
            "static"
        ],
        "parents": [
            "Lib\\Model"
        ],
        "lcom": 4,
        "length": 48,
        "vocabulary": 9,
        "volume": 152.16,
        "difficulty": 4.57,
        "effort": 695.57,
        "level": 0.22,
        "bugs": 0.05,
        "time": 39,
        "intelligentContent": 33.28,
        "number_operators": 16,
        "number_operands": 32,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 9,
        "loc": 42,
        "lloc": 33,
        "mi": 84.32,
        "mIwoC": 51.46,
        "commentWeight": 32.86,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.61,
        "relativeSystemComplexity": 36.61,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 2.43,
        "totalSystemComplexity": 146.43,
        "package": "Src\\Model\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Src\\Model\\Comment",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getComments",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCommentsAdmin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "insert",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Lib\\Model",
            "static",
            "static",
            "static",
            "static",
            "static"
        ],
        "parents": [
            "Lib\\Model"
        ],
        "lcom": 5,
        "length": 65,
        "vocabulary": 16,
        "volume": 260,
        "difficulty": 3.5,
        "effort": 910,
        "level": 0.29,
        "bugs": 0.09,
        "time": 51,
        "intelligentContent": 74.29,
        "number_operators": 16,
        "number_operands": 49,
        "number_operators_unique": 2,
        "number_operands_unique": 14,
        "cloc": 6,
        "loc": 44,
        "lloc": 38,
        "mi": 75.56,
        "mIwoC": 48.49,
        "commentWeight": 27.07,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 25.53,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 2.67,
        "totalSystemComplexity": 127.67,
        "package": "Src\\Model\\",
        "pageRank": 0.06,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    }
]